### ISSUE TITLE
Streamlit formatting problem when using linebreaks

### ISSUE THREAD

**Issue by Aran30** [BESSER-PEARL/bot-framework#21]
When using streamlit, a reply that contains linebreaks (\n) won't be formatted correctly.
Only once the message is reloaded do linebreaks appear.

The message's first appearance: 
![image](https://github.com/BESSER-PEARL/bot-framework/assets/50965489/fe162fef-b4d4-471b-a7bc-282dc2f8ef16)

Once follow up messages arrive: 

![image](https://github.com/BESSER-PEARL/bot-framework/assets/50965489/2e94a0a7-25fc-4deb-a796-86fc9cbf2cf0)

This seems somehow to be related to the function to type out messages instead of immediately pasting the entire message to the platform: 
https://github.com/BESSER-PEARL/bot-framework/blob/cccdd3eeda7193960f41d44be060f181ceddccc0/besser/bot/platforms/websocket/streamlit_ui.py#L127

**Comment by mgv99** [comment]
now we display a spinner to do the 'typing effect'
